//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clock11 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clock11.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea by Andreas L.
        ///Programmed by Andreas L..
        /// </summary>
        public static string strAboutText1 {
            get {
                return ResourceManager.GetString("strAboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string strApply {
            get {
                return ResourceManager.GetString("strApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock11.
        /// </summary>
        public static string strAppTitle {
            get {
                return ResourceManager.GetString("strAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string strCenter {
            get {
                return ResourceManager.GetString("strCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors:.
        /// </summary>
        public static string strColorPalette_Colors {
            get {
                return ResourceManager.GetString("strColorPalette_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Colors:.
        /// </summary>
        public static string strColorPalette_DefaultColors {
            get {
                return ResourceManager.GetString("strColorPalette_DefaultColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string strLeft {
            get {
                return ResourceManager.GetString("strLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/29/2021 2:23 PM.
        /// </summary>
        public static string strReleaseDate {
            get {
                return ResourceManager.GetString("strReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string strRight {
            get {
                return ResourceManager.GetString("strRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string strSettings {
            get {
                return ResourceManager.GetString("strSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Themes.
        /// </summary>
        public static string strSettings_PredefiniedThemes {
            get {
                return ResourceManager.GetString("strSettings_PredefiniedThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string strSettings_Theme {
            get {
                return ResourceManager.GetString("strSettings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock11 Settings.
        /// </summary>
        public static string strSettings_Title {
            get {
                return ResourceManager.GetString("strSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Theme.
        /// </summary>
        public static string strSettingsDialog_CustomTheme {
            get {
                return ResourceManager.GetString("strSettingsDialog_CustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color:.
        /// </summary>
        public static string strSettingsDialog_FontColor {
            get {
                return ResourceManager.GetString("strSettingsDialog_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family:.
        /// </summary>
        public static string strSettingsDialog_FontFamily {
            get {
                return ResourceManager.GetString("strSettingsDialog_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string strSettingsDialog_FontSize {
            get {
                return ResourceManager.GetString("strSettingsDialog_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Date/Time:.
        /// </summary>
        public static string strSettingsDialog_MarginDateTime {
            get {
                return ResourceManager.GetString("strSettingsDialog_MarginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Margin:.
        /// </summary>
        public static string strSettingsDialog_RightMargin {
            get {
                return ResourceManager.GetString("strSettingsDialog_RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        public static string strSettingsDialog_ShowSeconds {
            get {
                return ResourceManager.GetString("strSettingsDialog_ShowSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-Alignment:.
        /// </summary>
        public static string strSettingsDialog_TextAlignment {
            get {
                return ResourceManager.GetString("strSettingsDialog_TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin:.
        /// </summary>
        public static string strSettingsDialog_TopMargin {
            get {
                return ResourceManager.GetString("strSettingsDialog_TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock11 is already running!.
        /// </summary>
        public static string strSingleInstance_Message_AlreadyRunning {
            get {
                return ResourceManager.GetString("strSingleInstance_Message_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already running!.
        /// </summary>
        public static string strSingleInstance_Message_AlreadyRunning_Title {
            get {
                return ResourceManager.GetString("strSingleInstance_Message_AlreadyRunning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10.
        /// </summary>
        public static string strTheme_Windows10 {
            get {
                return ResourceManager.GetString("strTheme_Windows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 11 (Default).
        /// </summary>
        public static string strTheme_Windows11 {
            get {
                return ResourceManager.GetString("strTheme_Windows11", resourceCulture);
            }
        }
    }
}
